name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install
        run: pnpm install

      - name: Lint
        run: pnpm run lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install
        run: pnpm install

      - name: Typecheck
        run: pnpm run typecheck

  build-display:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 5.15.2
          setup-python: false
      - name: Setup MSVC
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64
      - name: Configure & Build
        uses: ashutoshvarma/action-cmake-build@master
        with:
          build-dir: ${{ runner.workspace }}/build
          cc: cl
          cxx: cl
          build-type: Release
          parallel: 4
      - run: |
          mkdir ${{ runner.workspace }}/build/rel
          cp ${{ runner.workspace }}/build/class-system-display.exe ${{ runner.workspace }}/build/rel
          windeployqt ${{ runner.workspace }}/build/rel/class-system-display.exe --no-translations --no-opengl-sw --no-system-d3d-compiler
      - name: Archive executable
        uses: actions/upload-artifact@v4
        with:
          name: windows-x86_64
          path: ${{ runner.workspace }}/build/rel
